<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Classe; use Illuminate\Http\Request; use Illuminate\Http\JsonResponse; use Illuminate\Validation\Rule; use Illuminate\Support\Facades\Log;
class ClasseController extends Controller {
    public function index(): JsonResponse { try { return response()->json(Classe::orderBy('nom')->get()); } catch (\Exception $e) { Log::error("Err index Classes: ".$e->getMessage()); return response()->json(['error'=>'Err load classes.'], 500); } }
    public function store(Request $request): JsonResponse { $validated = $request->validate(['id' => ['required','string','max:20',Rule::unique('classes'),'regex:/^[a-zA-Z0-9_-]+$/'], 'nom' => 'required|string|max:255|unique:classes,nom']); try { $classe = Classe::create($validated); return response()->json($classe, 201); } catch (\Exception $e) { Log::error("Err store Classe: ".$e->getMessage()); if ($e->getCode() == '23000') { return response()->json(['error' => "ID Classe existe déjà."], 409); } return response()->json(['error' => 'Err création classe.'], 500); } }
    public function show(Classe $classe): JsonResponse { return response()->json($classe); }
    public function update(Request $request, Classe $classe): JsonResponse { $validated = $request->validate(['nom' => ['required', 'string', 'max:255', Rule::unique('classes', 'nom')->ignore($classe->id)]]); try { $classe->update($validated); return response()->json($classe); } catch (\Exception $e) { Log::error("Err update Classe {$classe->id}: ".$e->getMessage()); return response()->json(['error'=>'Err màj classe.'], 500); } }
    public function destroy(Classe $classe): JsonResponse { try { $classe->delete(); return response()->json(['message' => 'Classe supprimée.'], 200); } catch (\Exception $e) { Log::error("Err destroy Classe {$classe->id}: ".$e->getMessage()); return response()->json(['error'=>'Err suppression classe.'], 500); } }
}