<?php
namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller; use App\Models\Matiere; use Illuminate\Http\Request; use Illuminate\Http\JsonResponse; use Illuminate\Support\Facades\Log;
class MatiereController extends Controller {
    public function index(): JsonResponse { try { $matieres = Matiere::with('classe:id,nom')->orderBy('nom')->get(['id', 'nom', 'classe_id']); return response()->json($matieres); } catch (\Exception $e) { Log::error("Err index Matieres: ".$e->getMessage()); return response()->json(['error'=>'Err load matieres.'], 500); } }
    public function store(Request $request): JsonResponse { $validated = $request->validate(['nom' => 'required|string|max:150', 'classe_id' => 'required|string|exists:classes,id']); try { $matiere = Matiere::create($validated); $matiere->load('classe:id,nom'); return response()->json($matiere, 201); } catch (\Exception $e) { Log::error("Err store Matiere: ".$e->getMessage()); return response()->json(['error'=>'Err création matière.'], 500); } }
    public function show(Matiere $matiere): JsonResponse { try { $matiere->load(['classe:id,nom', 'chapitres:id,nom,matiere_id']); return response()->json($matiere); } catch (\Exception $e) { Log::error("Err show Matiere {$matiere->id}: ".$e->getMessage()); return response()->json(['error'=>'Err load matière.'], 500); } }
    public function update(Request $request, Matiere $matiere): JsonResponse { $validated = $request->validate(['nom' => 'required|string|max:150', 'classe_id' => 'sometimes|required|string|exists:classes,id']); try { $matiere->update($validated); $matiere->load('classe:id,nom'); return response()->json($matiere); } catch (\Exception $e) { Log::error("Err update Matiere {$matiere->id}: ".$e->getMessage()); return response()->json(['error'=>'Err màj matière.'], 500); } }
    public function destroy(Matiere $matiere): JsonResponse { try { $matiere->delete(); return response()->json(['message' => 'Matière supprimée.'], 200); } catch (\Exception $e) { Log::error("Err destroy Matiere {$matiere->id}: ".$e->getMessage()); return response()->json(['error'=>'Err suppression matière.'], 500); } }
}